### ISSUE TITLE
Random read errors reading parquet file from HDFS, written by Spark (2.4)

### ISSUE THREAD

**Issue by loicdescotte** [mjakubowski84/parquet4s#120]
Hi,

I'm reading an HDFS directory with several parquet files like this : 

```scala
lazy val conf = new Configuration()

ParquetStreams.fromParquet[ParquetModel](s"$rootPath/$country/$path", ParquetReader.Options(hadoopConf = conf))
```

My problem is that I have random errors, sometimes it fails during the source reading, sometimes it does not fail at all with the same data.

Error examples : 

```
org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file hdfs://xxx/part-00005-6355a05a-9963-417b-94a5-f686d939addb.c000.gz.parquet


Caused by: org.apache.parquet.io.ParquetDecodingException: could not read page Page [bytes.size=1048652, valueCount=29129, uncompressedSize=1048652] in col [offerId] optional binary offerId (UTF8)
    at org.apache.parquet.column.impl.ColumnReaderImpl.readPageV1(ColumnReaderImpl.java:599)

Caused by: java.io.IOException: not a gzip file
```

Or sometimes : 

```
ParquetDecodingException: could not read page Page [bytes.size=124985, valueCount=124729, uncompressedSize=124985] in col [categoryId] required int64 categoryId
```

I thought the parquet files were corrupted but I'm able to read them without any problem using a spark shell. I've tried to write them with the spark parquet legacy format but it didn't solve the issue.

In my unit tests, I use `ParquetWriter.write`. In this case the reads always work.

Do you have any idea?

Thanks :)

**Comment by mjakubowski84** [comment]
That's interesting, indeed! If not the case that it fails randomly I would say that there can be the problem with the schema.
I can only thing of two things: try using exactly the same version of Parquet library (see transitive deps) that Spark is using. Parquet4s is tested against Spark so everything should be compatible...
Another: try increasing memory, maybe there's smth wrong with buffers during reading.

**Comment by loicdescotte** [comment]
Hi,
I've changed the lib version and increased the memory, it's still failing at the first read, then when I relaunch it seems to works better than before.

But I still have the same failures as before in the end. 

An other message I've seen in the stacktrace : 

> Caused by: java.io.IOException: too many length or distance symbols

**Comment by mjakubowski84** [comment]
What can I only say now is that you can search on internet for the clues, eg.: there two here: https://stackoverflow.com/questions/31648717/dataflow-gzip-textio-zipexception-too-many-length-or-distance-symbols (buggy compression lib on server or files are corrupted but Spark handles that somehow).
What I can suggest also is:
 - avoid reading content of the whole file into memory, process it record by record if possible and release the memory
 - maybe try different jdk? E.g. I use at home and at work latest jdk8 (adopted version, e.g.). Other versions sometimes generate strange problems.

**Comment by loicdescotte** [comment]
Thanks for the link,

> avoid reading content of the whole file into memory 

I'm using the akka stream source with `ParquetStreams.fromParquet[ParquetModel]` so I guess it works record by record? 

I'm also using JDK 8

Thanks

Loïc

**Comment by mjakubowski84** [comment]
@loicdescotte  After some thinking I start to believe that your problem is related to compression (it is one of the most common issues with Parquet files). 
If possible try other compression algorithm when producing Parquet files. Gzip is not the best choice in case of performance and parallelism. Try something better like Snappy or LZ4, I recommend the latter). 
If you had to rely on Gzip then check for issues in related libs in your deps and on host.

**Comment by loicdescotte** [comment]
Hi, 

I've tried with Snappy and I have almost the same issue : 

```
org.apache.parquet.io.ParquetDecodingException: Can not read value at 50296 in block 0 in file hdfs://xxx/profileId=25388/part-00000-c86a4df0-0a28-4be9-b9e6-97dfc9ad64fe.c000.snappy.parquet
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:251)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:132)
	at com.github.mjakubowski84.parquet4s.ParquetStreams$.$anonfun$fromParquet$2(ParquetStreams.scala:46)
	at akka.stream.impl.UnfoldResourceSource$$anon$1.onPull(UnfoldResourceSource.scala:43)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:551)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:434)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:55)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:51)
	at akka.stream.impl.fusing.ActorGraphInterpreter$RequestMore.execute(ActorGraphInterpreter.scala:273)
Caused by: org.apache.parquet.io.ParquetDecodingException: could not read page Page [bytes.size=1050173, valueCount=417, uncompressedSize=1050173] in col [offerJson] optional binary offerJson (UTF8)
	at org.apache.parquet.column.impl.ColumnReaderImpl.readPageV1(ColumnReaderImpl.java:599)
	at org.apache.parquet.column.impl.ColumnReaderImpl.access$300(ColumnReaderImpl.java:57)
	at org.apache.parquet.column.impl.ColumnReaderImpl$3.visit(ColumnReaderImpl.java:536)
	at org.apache.parquet.column.impl.ColumnReaderImpl$3.visit(ColumnReaderImpl.java:533)
	at org.apache.parquet.column.page.DataPageV1.accept(DataPageV1.java:95)
	at org.apache.parquet.column.impl.ColumnReaderImpl.readPage(ColumnReaderImpl.java:533)
	at org.apache.parquet.column.impl.ColumnReaderImpl.checkRead(ColumnReaderImpl.java:525)
	at org.apache.parquet.column.impl.ColumnReaderImpl.consume(ColumnReaderImpl.java:638)
	at org.apache.parquet.io.RecordReaderImplementation.read(RecordReaderImplementation.java:408)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:226)
Caused by: java.io.IOException: FAILED_TO_UNCOMPRESS(5)
	at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:98)
	at org.xerial.snappy.SnappyNative.rawUncompress(Native Method)
	at org.xerial.snappy.Snappy.uncompress(Snappy.java:547)
	at org.apache.parquet.hadoop.codec.SnappyDecompressor.decompress(SnappyDecompressor.java:69)
	at org.apache.parquet.hadoop.codec.NonBlockedDecompressorStream.read(NonBlockedDecompressorStream.java:51)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.apache.parquet.bytes.BytesInput$StreamBytesInput.toByteArray(BytesInput.java:263)
	at org.apache.parquet.bytes.BytesInput.toByteBuffer(BytesInput.java:214)
	at org.apache.parquet.bytes.BytesInput.toInputStream(BytesInput.java:223)
```

**Comment by mjakubowski84** [comment]
Well... then now the only idea I have is that you may have a corrupted disk storage...

**Comment by loicdescotte** [comment]
> you may have a corrupted disk storage

It's still weird as reading the same files works with Spark and with other applications using parquet reading with Spark.
I've tried with Scala 2.13 , as it seems it uses other dependencies (no spark deps?) and using Scala  2.13  + Snappy I have almost no error (but sometimes I have the `FAILED_TO_UNCOMPRESS` error again). I've managed to read several millions of lines with no issue on my second run (the first run failed with a `FAILED_TO_UNCOMPRESS`  error, on the same data set).
I don't know if it can help to understand the issue :)

**Comment by mjakubowski84** [comment]
Version for 2.13 has deps built under Scala 2.13. Spark deps are used only for testing the lib for compatibility (there's no Spark for Scala 2.13).

Spark usually restarts tasks when encounters issues. Did you check the logs if smth similar happens there?

If you claim that app behaves better under 2.13 then maybe check memory and CPU load? Scala 2.13 is slightly better optimised.

I can also encourage you to search for help on Parquet Github as this issue may be related to Parquet itself.

**Comment by loicdescotte** [comment]
I will check, thanks!

**Comment by mjakubowski84** [comment]
Hey @loicdescotte , any success? I'd like to cleanup issues here :)

**Comment by loicdescotte** [comment]
No success sorry, we have switched to another solution (no parquet file).
No idea if it should be closed or not

**Comment by mjakubowski84** [comment]
Good to see that you found some (completely different) solution for your problem. 
I close the ticket as your original issue is not directly related to Parquet4s but to Parquet core library.
