### ISSUE TITLE
Local Files require hadoop backend

### ISSUE THREAD

**Issue by bbstilson** [mjakubowski84/parquet4s#159]
According to the README, one should be able to read local files without any further dependencies, but this does not appear to be true.

I have tried appending `file://` to my local file path string as well as just using the path string itself.

Here is the stack trace:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at com.github.mjakubowski84.parquet4s.ParquetReader$Options$.apply$default$2(ParquetReader.scala:37)
        at com.github.mjakubowski84.parquet4s.ParquetReader$.read$default$2(ParquetReader.scala:69)
        at Parser$.$anonfun$parse$1(Parser.scala:30)
        at Parser$.$anonfun$parse$1$adapted(Parser.scala:24)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at Parser$.parse(Parser.scala:24)
        at MakeSuggestions$.run(MakeSuggestions.scala:68)
        at MakeSuggestions$.$anonfun$main$1(MakeSuggestions.scala:50)
        at MakeSuggestions$.$anonfun$main$1$adapted(MakeSuggestions.scala:50)
        at scala.Option.foreach(Option.scala:437)
        at MakeSuggestions$.main(MakeSuggestions.scala:50)
        at MakeSuggestions.main(MakeSuggestions.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 12 more
```

Using `ivy"com.github.mjakubowski84::parquet4s-core:1.3.1"` with Scala 2.13.2.

**Comment by mjakubowski84** [comment]
Maybe that's misleading as readme about local files is pretty old but down
the file, in section about modules, it is mentioned that you have to define
your version of hadoop-client. Hadoop is made provided. By saying "no
configuration" I mean that you do not have to set anything in the options.
But "out of the box" is wrong, indeed.

pt., 31 lip 2020, 07:44 użytkownik Brandon Stilson <notifications@github.com>
napisał:

**Comment by bbstilson** [comment]
Ah got it! Thanks so much. 

Would it be acceptable to open a PR to update the README?

**Comment by mjakubowski84** [comment]
Of course!

pt., 31 lip 2020, 09:04 użytkownik Brandon Stilson <notifications@github.com>
napisał:
