### ISSUE TITLE
Local file system expected instead of S3

### ISSUE THREAD

**Issue by malonsocasas** [mjakubowski84/parquet4s#186]
Hello again ! 

I have another small issue when retrieving Parquet statistics from a file on S3. What I understand is that the file is expected to be on the local file system instead of S3. 

This is the error I get:
```
Exception in thread "main" java.lang.IllegalArgumentException: Wrong FS: s3a://my-bucket/my-file.parquet, expected: file:///
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:776)
	at org.apache.hadoop.fs.RawLocalFileSystem.pathToFile(RawLocalFileSystem.java:89)
	at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:487)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1941)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1983)
	at org.apache.hadoop.fs.ChecksumFileSystem.listStatus(ChecksumFileSystem.java:719)
	at com.github.mjakubowski84.parquet4s.Stats$.apply(Stats.scala:110)
	at com.github.mjakubowski84.parquet4s.ParquetReader$.com$github$mjakubowski84$parquet4s$ParquetReader$$newParquetIterable(ParquetReader.scala:64)
	at com.github.mjakubowski84.parquet4s.ParquetReader$$anon$1.read(ParquetReader.scala:99)
	at com.github.mjakubowski84.parquet4s.ParquetReader$.read(ParquetReader.scala:92)
```

The problem seems to be at this line: https://github.com/mjakubowski84/parquet4s/blob/v1.8.1/core/src/main/scala/com/github/mjakubowski84/parquet4s/Stats.scala#L109

The actual behavior seems to always select the default FS (which is Local) instead of getting the one associated to the schema of the path (here it would be `s3a`).

I will submit a fix on a new PR if that seems relevant to you.

**Comment by mjakubowski84** [comment]
Thanks, it looks like that I didn't test the new feature, well. PR will be appreciated.

**Comment by malonsocasas** [comment]
Yeah that's what I was thinking about too. I'll try to add a unit test

**Comment by mjakubowski84** [comment]
@malonsocasas As this is a critical bug I already released a bugfix version. Please try it and tell me if everything is fine now.

**Comment by malonsocasas** [comment]
Yes it works perfectly, thanks for that ! 

I tried to write a small test to check this issue. You can add it to `StatsSpec` if you think it is useful : 

```
class CustomFileSystem() extends RawLocalFileSystem() {
  override def getUri: URI = URI.create("custom:///")
}

class StatsSpec ... {
      "Stats" should "not throw exception with a handled non local scheme path" in {
            val hadoopConf = new Configuration()
            hadoopConf.setClass("fs.custom.impl", classOf[CustomFileSystem], classOf[FileSystem])
            val options = ParquetReader.Options(hadoopConf = hadoopConf)
            noException should be thrownBy Stats(s"custom:///$path/0.parquet", options = options)
      }
}
```

There may be better ways to test that with `jimfs` for example, but this works :)

**Comment by mjakubowski84** [comment]
Thanks, will try to add those to the code.
