### ISSUE TITLE
Reading partitioned data fails when columns have special characters

### ISSUE THREAD

**Issue by sndnv** [mjakubowski84/parquet4s#214]
While testing some code that uses `parquet4s`, I noticed that in some cases partitioned data written by the library cannot be read back. For example:

```scala
  // ... imports, actor system, execution context, etc

  final case class Message(a: String, b: String, c: Double)

  val outgoing: List[Message] = List(
    Message(a = "message-A", b = "0", c = 0.42),
    Message(a = "message-A", b = "0", c = 1.42),
    Message(a = "message-A", b = "0", c = 2.42),
    Message(a = "message-B", b = "0", c = 3.42),
    Message(a = "message-B", b = "1", c = 3.42)
  )

  Source(outgoing)
      .via(
        flow = ParquetStreams
          .viaParquet[Message]("target/parquet/test")
          .withPartitionBy(partitionBy = "a") // partition by the first field in `Message`
          .withMaxCount(maxCount = 3)
          .withMaxDuration(maxDuration = 60.seconds)
          .withWriteOptions(parquet4s.ParquetWriter.Options(ParquetFileWriter.Mode.OVERWRITE))
          .build()
      )
      .run()
      .await

val incoming = ParquetStreams
      .fromParquet[Message]
      .read(path)
      .runFold(List.empty[Message])(_ :+ _)
      .await

println(s"Outgoing: [${outgoing.size}], Incoming: [${incoming.size}]")
```

The expectation would be to read the same data back and see `Outgoing: [5], Incoming: [5]` on the console. Instead, an exception is thrown:

```
java.io.FileNotFoundException: /<path to private repo>/target/parquet/test/a=message-B (Is a directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileInputStream.<init>(RawLocalFileSystem.java:113)
	at org.apache.hadoop.fs.RawLocalFileSystem.open(RawLocalFileSystem.java:215)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:156)
	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:356)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:945)
	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:773)
	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:657)
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:152)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
	at com.github.mjakubowski84.parquet4s.ParquetSource$.$anonfun$createSource$3(ParquetSource.scala:98)
        ...
```
Removing the `-` in the first field of the case class (i.e. going from `message-B` to `messageB`) fixes the issue and the output is as expected.

---

I managed to track down the problem to [this regex](https://github.com/mjakubowski84/parquet4s/blob/v1.9.1/akka/src/main/scala/com/github/mjakubowski84/parquet4s/IOOps.scala#L22) which allows very few characters in the partition value: alphanumeric plus `.` and `_` but based on the [S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html), a few more characters are fine to use.

**Comment by mjakubowski84** [comment]
Thank you for the PR! I will check this out in few hours. If all is fine then we will release the bugfix.

**Comment by mjakubowski84** [comment]
There's an issue with https://sks-keyservers.net/. Sonatype rejects releases as it cannot verify the keys. Let's try tomorrow again.

**Comment by sndnv** [comment]
Alright :) Thanks for looking into this and merging the PR!

**Comment by mjakubowski84** [comment]
Keyserver is up again. Jars are published.

**Comment by sndnv** [comment]
Great, thanks!
