### ISSUE TITLE
Branch V1.9 write java.sql.Timestamp  type value exception

### ISSUE THREAD

**Issue by fywxin** [mjakubowski84/parquet4s#239]
- exception

```scala
Exception in thread "main" java.lang.UnsupportedOperationException: org.apache.parquet.column.values.dictionary.DictionaryValuesWriter$PlainLongDictionaryValuesWriter
	at org.apache.parquet.column.values.ValuesWriter.writeBytes(ValuesWriter.java:103)
	at org.apache.parquet.column.values.fallback.FallbackValuesWriter.writeBytes(FallbackValuesWriter.java:172)
```

- key code

```scala
  // timestamp field
  val Ts         = "ts"

  // generic Object
   (1L, "Alice", LocalDate.of(2000, 1, 1), new Timestamp(2222, 2, 2, 12, 44, 32, 0)),

// to RowParquetRecord
RowParquetRecord.empty
      .add(ID, id, vcc)
      .add(Name, name, vcc)
      .add(Birthday, birthday, vcc)
      .add(Ts, ts, vcc)

//schema
      .addField(Types.primitive(INT64, OPTIONAL).as(LogicalTypeAnnotation.timestampType(true, LogicalTypeAnnotation.TimeUnit.MILLIS)).named(Ts))

//read ts file
val ts = record.get[LocalDateTime](Ts, vcc)

```

- full example code with WriteAndReadGenericApp
```scala
package com.github.mjakubowski84.parquet4s.core

import java.time.{LocalDate, LocalDateTime, ZoneOffset}
import java.util.TimeZone

import com.github.mjakubowski84.parquet4s.{ParquetReader, ParquetWriter, RowParquetRecord, ValueCodecConfiguration}
import org.apache.parquet.schema.PrimitiveType.PrimitiveTypeName.{BINARY, INT32, INT64}
import org.apache.parquet.schema.Type.Repetition.{OPTIONAL, REQUIRED}
import org.apache.parquet.schema.{LogicalTypeAnnotation, MessageType, OriginalType, Types}
import java.nio.file.Files
import java.sql.Timestamp

import org.apache.parquet.hadoop.ParquetFileWriter

object WriteAndReadGenericApp extends App {

  val ID         = "id"
  val Name       = "name"
  val Birthday   = "birthday"
  val Ts         = "ts"
  val SchemaName = "user_schema"

  val path = Files.createTempDirectory("example").toString
  val vcc  = ValueCodecConfiguration(TimeZone.getTimeZone(ZoneOffset.UTC))

  val users = List(
    (1L, "Alice", LocalDate.of(2000, 1, 1), new Timestamp(2222, 2, 2, 12, 44, 32, 0)),
    (2L, "Bob", LocalDate.of(1980, 2, 28), new Timestamp(2222, 2, 2, 12, 44, 32, 0)),
    (3L, "Cecilia", LocalDate.of(1977, 3, 15), new Timestamp(2222, 2, 2, 12, 44, 32, 0))
  ).map { case (id, name, birthday, ts) =>
    RowParquetRecord.empty
      .add(ID, id, vcc)
      .add(Name, name, vcc)
      .add(Birthday, birthday, vcc)
      .add(Ts, ts, vcc)
  }

  // write
  implicit val schema: MessageType = Types
    .buildMessage()
    .addField(Types.primitive(INT64, REQUIRED).as(LogicalTypeAnnotation.intType(64, true)).named(ID))
    .addField(Types.primitive(BINARY, OPTIONAL).as(LogicalTypeAnnotation.stringType()).named(Name))
    .addField(Types.primitive(INT32, OPTIONAL).as(LogicalTypeAnnotation.dateType()).named(Birthday))
      .addField(Types.primitive(INT64, OPTIONAL).as(LogicalTypeAnnotation.timestampType(true, LogicalTypeAnnotation.TimeUnit.MILLIS)).named(Ts))
    .named(SchemaName)

  val writerOptions = ParquetWriter.Options(
    writeMode = ParquetFileWriter.Mode.OVERWRITE
  )

  ParquetWriter.writeAndClose(s"$path/users.parquet", users, writerOptions)

  //read
  val readData = ParquetReader.read[RowParquetRecord](path)
  try readData.foreach { record =>
    val id       = record.get[Long](ID, vcc)
    val name     = record.get[String](Name, vcc)
    val birthday = record.get[LocalDate](Birthday, vcc)
    val ts = record.get[LocalDateTime](Ts, vcc)
    println(s"User[$ID=$id,$Name=$name,$Birthday=$birthday],$Ts=$ts]")
  } finally readData.close()

}

```

mjakubowski84, please help me, thank you so much~

**Comment by mjakubowski84** [comment]
Hi!

Not sure if this is the cause, but please use this for schema of timestamps: https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/Schema.scala#L204
and this for schema of dates: https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/Schema.scala#L191

**Comment by fywxin** [comment]
awsome!
thanks mjakubowski84 help!

wrong code:
```scala
.addField(Types.primitive(INT64, OPTIONAL).as(LogicalTypeAnnotation.timestampType(true, LogicalTypeAnnotation.TimeUnit.MILLIS)).named(Ts))

```` 

correct code:
```scala
.addField(SchemaDef.primitive(INT96, required = false).typed[java.sql.Timestamp].apply(Ts))

````
