### ISSUE TITLE
Unable to save to HDFS using `sc.hadoopConfiguration`

### ISSUE THREAD

**Issue by cbcoutinho** [mjakubowski84/parquet4s#241]
Hey, I'd really like to use this library but I'm having trouble following the example using Hadoop Configuration programatically ([link](https://mjakubowski84.github.io/parquet4s/docs/quick_start/#passing-hadoop-configs-programmatically))

System:
hadoop 2.7.4
sbt: 1.5.5
scala: 2.12.15

Specifically, when I try to write the data to parquet using the `sbt console` I'm greeted with the following Exception:

```java
ParquetWriter.of[User].options(writerOptions).writeAndClose(Path("/tmp/spark-warehouse/output/file.parquet"), users)
java.lang.InternalError: Malformed class name
  at java.lang.Class.getSimpleName(Class.java:1330)
  at java.lang.Class.getCanonicalName(Class.java:1399)
  at com.github.mjakubowski84.parquet4s.ParquetSchemaResolver$$anon$1.schemaName(ParquetSchemaResolver.scala:83)
  at com.github.mjakubowski84.parquet4s.ParquetSchemaResolver$.resolveSchema(ParquetSchemaResolver.scala:57)
  at com.github.mjakubowski84.parquet4s.ParquetWriterImpl.<init>(ParquetWriter.scala:185)
  at com.github.mjakubowski84.parquet4s.ParquetWriter$BuilderImpl.build(ParquetWriter.scala:111)
  at com.github.mjakubowski84.parquet4s.ParquetWriter$BuilderImpl.writeAndClose(ParquetWriter.scala:113)
  ... 31 elided
```

Running the example in a spark-shell (spark 3.1.2 - standalone mode) also doesn't work, but produces a different exception:

```java
ParquetWriter.of[User].options(writerOptions).writeAndClose(Path("/tmp/spark-warehouse/output/file.parquet"), users)
java.lang.IllegalAccessError: class org.apache.parquet.schema.LogicalTypeAnnotation$DecimalLogicalTypeAnnotation tried to access method 'org.apache.parquet.schema.PrimitiveStringifier org.apache.parquet.schema.PrimitiveStringifier.createDecimalStringifier(int)' (org.apache.parquet.schema.LogicalTypeAnnotation$DecimalLogicalTypeAnnotation is in unnamed module of loader scala.reflect.internal.util.ScalaClassLoader$URLClassLoader @24954e82; org.apache.parquet.schema.PrimitiveStringifier is in unnamed module of loader 'app')
  at org.apache.parquet.schema.LogicalTypeAnnotation$DecimalLogicalTypeAnnotation.<init>(LogicalTypeAnnotation.java:453)
  at org.apache.parquet.schema.LogicalTypeAnnotation$DecimalLogicalTypeAnnotation.<init>(LogicalTypeAnnotation.java:445)
  at org.apache.parquet.schema.LogicalTypeAnnotation.decimalType(LogicalTypeAnnotation.java:264)
  at com.github.mjakubowski84.parquet4s.LogicalTypes$.<init>(Schema.scala:75)
  at com.github.mjakubowski84.parquet4s.LogicalTypes$.<clinit>(Schema.scala)
  at com.github.mjakubowski84.parquet4s.SchemaDefs.$init$(Schema.scala:155)
  at com.github.mjakubowski84.parquet4s.ParquetSchemaResolver$.<init>(ParquetSchemaResolver.scala:35)
  at com.github.mjakubowski84.parquet4s.ParquetSchemaResolver$.<clinit>(ParquetSchemaResolver.scala)
  ... 47 elided
```

I've tried this both in the `sbt console` and `spark-shell` - neither of which work for me. Could you help interpret these stack traces?

Any help greatly appreciated.

**Comment by mjakubowski84** [comment]
Google says that this is issue with Scala and Java 8: https://github.com/scala/bug/issues/2034.
Avoid defining schema classes deeply in other objects and/or other classes.
Or use Java 9+.

**Comment by mjakubowski84** [comment]
Out of curiosity, which version and distribution of JVM are you using? Because Parquet4s is tested and compiled against JVM 8. Tests include nested class definitions, even in anonymous classes - getCanonicalName should return then `null` instead throwing an error.

**Comment by mjakubowski84** [comment]
Regarding issue with spark-shell - it looks like dependency conflict. Spark ships its own libs, hadoop and Parquet, so you have several options:
 - shade Parquet4s: https://mungingdata.com/apache-spark/shading-dependencies-with-sbt/
 - do not use Parquet4s in Spark and use Spark's capabilities for reading and writing Parquet

**Comment by cbcoutinho** [comment]
Hi there, that's correct - I'm on JVM 8. This is also part of a spark project so dependency conflict could be where the problem lies.

I'm not sure about what needs to to be shaded - does parquet4s get shaded or the spark/parquet lib provided by the environment?

**Comment by mjakubowski84** [comment]
To sum up - you have 2 (or even 3) unrelated issues:

 1) Scala issue with deeply nested classes when running on old versions of JVM (scala/bug#2034). In order to understand this problem I need to know which exactly version and distribution of JVM you are using. You mention that you use `sbt console` - what is the first line that sbt prints for you? For example I have `[info] welcome to sbt 1.6.1 (Temurin Java 1.8.0_312)`.
 2) It is a common developer's problem that Spark libraries are in conflict with dependencies of the job. That's why you have to be careful when building your assembly. Parquet4s is based on official Java Parquet libraries: https://github.com/apache/parquet-mr. They are also used by Spark and I see that 3.1.2 uses quite an old version https://github.com/apache/spark/blob/v3.1.2/pom.xml#L138 which may cause a classpath conflict. Because of that reason, if you really want to use Parquet4s in Spark, you have to shade all `org.apache.parquet.*` packages in your job.
 3) Why do you want to use Parquet4s in Spark job? Reading and writing Parquet is one of the basic features of Spark - you do not need to use any other library for that. The story behind Parquet4s is that I didn't want to start Spark when doing IO on small datasets - starting Spark for that was like firing from bazooka to a fly.

**Comment by cbcoutinho** [comment]
Thanks for the thorough writeup - I'm still getting used to the JVM jargon surrounding scala.

I'm running java 8,  `OpenJDK 1.8.0_312`, locally to mirror the version of java running on the clusters. Even if I could change it locally I still aim to get it running there. I'll look into shading libraries in the assembly - that appears to be the best bet.

The reason I'm trying to use this library along with Spark is because writing Parquet to HDFS involves coordinating the distributed write from the driver. Due to the severity of the input skew (ie. most events belong to 2 or 3 event types out of 200), coordinating the write of each type via the driver is a significant contribution to the total job time.

Instead of coordinating the work via the driver, we're now just coordinating the filenames using the driver and managing the file read/writes using the executors themselves. It's possible to read/write JSON on HDFS using `FSData(Output|Input)Stream`, and I'm assuming something similar would be possible with parquet

BTW I just created an empty project (without Spark) and am able to read/write parquet files from the local file system, but the real challenge is to include this in a spark project

Thanks for the prompt help
