### ISSUE TITLE
Is schema backwards compatibility on projections possible?

### ISSUE THREAD

**Issue by Kevin-Covey** [mjakubowski84/parquet4s#306]
I'm trying to read two files that have differing schemas, where the second schema has an optional column that isn't defined on the first schema.  Aside from doing a `generic` read, I haven't been able to get this to work.  I'm not sure if this is just not possible, or if I'm doing it wrong.

Example Code using parquet4s-fs2 2.10.0:
```scala
object Example extends IOApp {
  private val vcc = ValueCodecConfiguration.Default

  override def run(args: List[String]): IO[ExitCode] = {
    val schemaWithOneOptionalColumn = Types.buildMessage()
      .addField(primitive(BINARY, REQUIRED).as(stringType()).named("requiredColumn"))
      .addField(optional(DOUBLE).named("optionalColumn1"))
      .named("schema_with_two_columns")

    val recordWithOneOptionalColumn = RowParquetRecord
      .emptyWithSchema(schemaWithOneOptionalColumn.getFields.asScala.map(_.getName))
      .updated("partition1", "a", vcc)
      .updated("partition2", "b", vcc)
      .updated("requiredColumn", "some value 1", vcc)
      .updated("optionalColumn1", 1.0, vcc)

    val schemaWithTwoOptionalColumns = Types.buildMessage()
      .addField(primitive(BINARY, REQUIRED).as(stringType()).named("requiredColumn"))
      .addField(optional(DOUBLE).named("optionalColumn1"))
      .addField(optional(DOUBLE).named("optionalColumn2"))
      .named("schema_with_three_columns")

    val recordWithTwoOptionalColumns = RowParquetRecord
      .emptyWithSchema(schemaWithOneOptionalColumn.getFields.asScala.map(_.getName))
      .updated("partition1", "a", vcc)
      .updated("partition2", "c", vcc)
      .updated("requiredColumn", "some value 2", vcc)
      .updated("optionalColumn1", 2.0, vcc)
      .updated("optionalColumn2", 3.0, vcc)

    (Stream(recordWithOneOptionalColumn).through(write(schemaWithOneOptionalColumn))
      >> Stream(recordWithTwoOptionalColumns).through(write(schemaWithTwoOptionalColumns)))
      .append(readAllGeneric)
      // .append(readAllAsType)
      // .append(readAllProjectedAsType)
      // .append(readAllProjectedGeneric)
      // .append(readAllProjectedGenericWithMessageType)
      .compile
      .drain
      .as(ExitCode.Success)
  }

  private val writeOptions: ParquetWriter.Options = ParquetWriter.Options(
    writeMode = ParquetFileWriter.Mode.OVERWRITE,
  )

  private def write(schema: MessageType): Pipe[IO, RowParquetRecord, RowParquetRecord] = {
    viaParquet[IO]
      .generic
      .options(writeOptions)
      .partitionBy(ColumnPath("partition1"), ColumnPath("partition2"))
      .write(Path("target/parquet/"), schema)
  }

  private val readOptions = {
    val hadoopConf = new Configuration()
    hadoopConf.setBoolean("parquet.strict.typing", false)

    ParquetReader.Options(hadoopConf = hadoopConf)
  }

  private val readAllGeneric =
    fromParquet[IO]
      .generic
      .read(Path("target/parquet"))
      .printlns

  case class MyProjection(requiredColumn: String, optionalColumn2: Option[Double])

  private val readAllAsType =
    fromParquet[IO]
      .as[MyProjection]
      .options(readOptions)
      .read(Path("target/parquet"))
      .printlns

  private val readAllProjectedAsType =
    fromParquet[IO]
      .projectedAs[MyProjection]
      .options(readOptions)
      .read(Path("target/parquet"))
      .printlns

  private val readAllProjectedGeneric =
    fromParquet[IO]
      .projectedGeneric(
        TypedColumnPath[String](ColumnPath("requiredColumn")),
        TypedColumnPath[Double](ColumnPath("optionalColumn2")),
      )
      .options(readOptions)
      .read(Path("target/parquet"))
      .printlns

  private val readAllProjectedGenericWithMessageType = {
    val projectionSchema = Types.buildMessage()
      .addField(primitive(BINARY, REQUIRED).as(stringType()).named("requiredColumn"))
      .addField(optional(DOUBLE).named("optionalColumn2"))
      .named("projection_schema")

    fromParquet[IO]
      .projectedGeneric(projectionSchema)
      .options(readOptions)
      .read(Path("target/parquet"))
      .printlns
  }

}
```

1) `readAllGeneric` works, no problem.  
2) `readAllAsType` fails with the following exception:
```
com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$DecodingException: Missing required field optionalColumn2 in a record: RowParquetRecord(requiredColumn=BinaryValue(Binary{12 constant bytes, [115, 111, 109, 101, 32, 118, 97, 108, 117, 101, 32, 49]}),optionalColumn1=DoubleValue(1.0),partition1=BinaryValue(Binary{"a"}),partition2=BinaryValue(Binary{"b"}))
	at com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$DecodingException$.apply(ParquetRecordDecoder.scala:34)
	at com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$given_ParquetRecordDecoder_Fields.decode(ParquetRecordDecoder.scala:63)
	at com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$given_ParquetRecordDecoder_Fields.decode(ParquetRecordDecoder.scala:51)
	at com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$given_ParquetRecordDecoder_Fields.decode(ParquetRecordDecoder.scala:61)
	at com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$given_ParquetRecordDecoder_Fields.decode(ParquetRecordDecoder.scala:51)
	at com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$derived.decode(ParquetRecordDecoder.scala:70)
	at com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$derived.decode(ParquetRecordDecoder.scala:69)
	at com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$.decode(ParquetRecordDecoder.scala:42)
	at com.github.mjakubowski84.parquet4s.parquet.reader$.$anonfun$3$$anonfun$1(reader.scala:147)
	at delay @ com.github.mjakubowski84.parquet4s.parquet.reader$.$anonfun$3(reader.scala:147)
	at map @ fs2.Chunk.traverse(Chunk.scala:395)
```
3) `readAllProjectedAsType` and `readAllProjectedGeneric` both fail with the same exception, and I don't understand why it's saying that `requiredColumn` is found to be optional, since I declared it as required in the schema when writing to the file.
```
org.apache.parquet.io.InvalidRecordException: optional binary requiredColumn (STRING) found: expected required binary requiredColumn (STRING)
	at org.apache.parquet.schema.Type.checkContains(Type.java:353)
	at org.apache.parquet.schema.PrimitiveType.checkContains(PrimitiveType.java:699)
	at org.apache.parquet.schema.GroupType.checkGroupContains(GroupType.java:349)
	at org.apache.parquet.schema.MessageType.checkContains(MessageType.java:124)
	at org.apache.parquet.hadoop.api.ReadSupport.getSchemaForRead(ReadSupport.java:56)
	at com.github.mjakubowski84.parquet4s.ParquetReadSupport.init$$anonfun$1(ParquetReadSupport.scala:33)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:675)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:669)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:933)
	at com.github.mjakubowski84.parquet4s.ParquetReadSupport.init(ParquetReadSupport.scala:33)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:183)
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:166)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
	at com.github.mjakubowski84.parquet4s.ParquetIterator.preRead(ParquetIterator.scala:30)
	at com.github.mjakubowski84.parquet4s.ParquetIterator.hasNext(ParquetIterator.scala:35)
	at fs2.Stream$PartiallyAppliedFromIterator$.getNextChunk$1$$anonfun$1$$anonfun$1(Stream.scala:3480)
	at map @ fs2.Stream$PartiallyAppliedFromIterator$.getNextChunk$1(Stream.scala:3482)
```
4) `readAllProjectedGenericWithMessageType` fails with:
```
org.apache.parquet.io.InvalidRecordException: optionalColumn2 not found in message schema_with_two_columns {
  required binary requiredColumn (STRING);
  optional double optionalColumn1;
}

	at org.apache.parquet.schema.GroupType.getFieldIndex(GroupType.java:176)
	at org.apache.parquet.schema.GroupType.getType(GroupType.java:208)
	at org.apache.parquet.schema.GroupType.checkGroupContains(GroupType.java:348)
	at org.apache.parquet.schema.MessageType.checkContains(MessageType.java:124)
	at org.apache.parquet.hadoop.api.ReadSupport.getSchemaForRead(ReadSupport.java:56)
	at com.github.mjakubowski84.parquet4s.ParquetReadSupport.init$$anonfun$1(ParquetReadSupport.scala:33)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:675)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:669)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:933)
	at com.github.mjakubowski84.parquet4s.ParquetReadSupport.init(ParquetReadSupport.scala:33)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:183)
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:166)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
	at com.github.mjakubowski84.parquet4s.ParquetIterator.preRead(ParquetIterator.scala:30)
	at com.github.mjakubowski84.parquet4s.ParquetIterator.hasNext(ParquetIterator.scala:35)
	at fs2.Stream$PartiallyAppliedFromIterator$.getNextChunk$1$$anonfun$1$$anonfun$1(Stream.scala:3480)
	at map @ fs2.Stream$PartiallyAppliedFromIterator$.getNextChunk$1(Stream.scala:3482)
```

**Comment by mjakubowski84** [comment]
Hi!

Such behaviour is expected.
Your `readGeneric` reads Parquet files as they are without any projection.
Other ways do the projection, that is, they enforce the schema on the read
file. If the schema of the file (encoded in the metadata of Parquet file)
conflicts with the enforced schema then you get an exception.
You seem to have heterogeneous files in a single directory and that's an
issue for the projection. Parquet expects that all files have that optional
column defined in their metadata but they don't!
The solution is that you have to read files with conflicting schema
separately or abandon the projection.

If you just use projection to turn record to a case class then you have
`as` function for that.

I hope that it helps.

pt., 21 lip 2023, 18:21 użytkownik Kevin Covey ***@***.***>
napisał:
