### ISSUE TITLE
Limitation in handling large decimal numbers

### ISSUE THREAD

**Issue by viniciuspnu** [mjakubowski84/parquet4s#365]
### Describe the problem

In the current implementation, there's a limitation in handling large decimal numbers:
- Decimals [are rescaled to have 18 decimal places](https://github.com/mjakubowski84/parquet4s/blob/6c252482a550af8a0977332614fd7da1c1327b8f/core/src/main/scala/com/github/mjakubowski84/parquet4s/Decimals.scala#L16) (scale = 18)
- The unscaled value [must fit in 16 bytes](https://github.com/mjakubowski84/parquet4s/blob/6c252482a550af8a0977332614fd7da1c1327b8f/core/src/main/scala/com/github/mjakubowski84/parquet4s/Decimals.scala#L11) (128 bits, with 1 bit for sign)
- This limits the integer part to 21 digits maximum

Example of current maximum supported number:
- Formatted: 999...999 (21 digits).999999999999999999 (18 digits)
- Unscaled: 999...999999999999999999999 (39 digits)

Any number with 22 digits in the integer part causes an overflow due to exceeding the 16-byte storage capacity after rescaling.

This limitation was found while using the [Flink/Delta Connector](https://github.com/delta-io/delta/tree/master/connectors/flink) when reading Parquet checkpoint files. The limitation manifests as a `BufferOverflowException` when trying to process decimal values that exceed the current constraints.

#### Steps to Reproduce
- Try to read a Parquet file containing a decimal value with 22 digits in the integer part

#### Further details
```
shadedelta.org.apache.parquet.io.ParquetDecodingException: Can not read value at 15 in block 0 in file s3a://some-bucket/some-delta-table/_delta_log/00000000000000000232.checkpoint.parquet
	at shadedelta.org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:254)
	at shadedelta.org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:132)
	at shadedelta.com.github.mjakubowski84.parquet4s.ParquetIterableImpl$$anon$3.hasNext(ParquetReader.scala:144)
	at scala.collection.IterableLike.copyToArray(IterableLike.scala:255)
	at scala.collection.IterableLike.copyToArray$(IterableLike.scala:251)
	at shadedelta.com.github.mjakubowski84.parquet4s.ParquetIterableImpl.copyToArray(ParquetReader.scala:126)
	at scala.collection.TraversableOnce.copyToArray(TraversableOnce.scala:334)
	at scala.collection.TraversableOnce.copyToArray$(TraversableOnce.scala:333)
	at shadedelta.com.github.mjakubowski84.parquet4s.ParquetIterableImpl.copyToArray(ParquetReader.scala:126)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:342)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at shadedelta.com.github.mjakubowski84.parquet4s.ParquetIterableImpl.toArray(ParquetReader.scala:126)
	at io.delta.standalone.internal.SnapshotImpl.$anonfun$loadInMemory$3(SnapshotImpl.scala:284)
        ...
Caused by: java.nio.BufferOverflowException
	at java.base/java.nio.HeapByteBuffer.put(Unknown Source)
	at java.base/java.nio.ByteBuffer.put(Unknown Source)
	at shadedelta.com.github.mjakubowski84.parquet4s.Decimals$.binaryFromDecimal(Decimals.scala:36)
	at shadedelta.com.github.mjakubowski84.parquet4s.Decimals$.rescaleBinary(Decimals.scala:20)
	at shadedelta.com.github.mjakubowski84.parquet4s.ParquetRecordConverter$DecimalConverter.addBinary(ParquetReadSupport.scala:133)
	at shadedelta.org.apache.parquet.column.impl.ColumnReaderBase$2$6.writeValue(ColumnReaderBase.java:390)
	at shadedelta.org.apache.parquet.column.impl.ColumnReaderBase.writeCurrentValueToConverter(ColumnReaderBase.java:440)
	at shadedelta.org.apache.parquet.column.impl.ColumnReaderImpl.writeCurrentValueToConverter(ColumnReaderImpl.java:30)
	at shadedelta.org.apache.parquet.io.RecordReaderImplementation.read(RecordReaderImplementation.java:406)
	at shadedelta.org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:229)
	...
```

**Comment by mjakubowski84** [comment]
Yes, Parquet4s rescales all decimals to the default 38 precision and scale of 12. It is encoded as a 16-byte array.
It was never requested to support any other decimals, so the responsible logic has remained the same since the very first versions of the library.

However, if the change is required, I suggest adding the possibility of providing a custom decimal format, for example, similar to how timestamp formats can be provided: https://mjakubowski84.github.io/parquet4s/docs/records_and_schema/#supported-types, https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/TimestampFormat.scala.

Feel free to propose a PR.

**Comment by mjakubowski84** [comment]
@viniciuspnu Support of decimals got substantially changed in https://github.com/mjakubowski84/parquet4s/releases/tag/v2.21.0. The issue should be fixed now. Please verify.
